# Generated by Django 5.1.5 on 2025-06-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('bus_number', models.CharField(max_length=20)),
                ('arrival_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
