# Generated by Django 5.1.5 on 2025-06-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='bus_number',
            field=models.CharField(max_length=200),
        ),
    ]
