# Generated by Django 5.1.5 on 2025-06-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstop', '0002_alter_busstop_bus_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='bus_number',
        ),
    ]
