# Generated by Django 5.2 on 2025-06-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stop_id', models.CharField(max_length=255, unique=True)),
                ('BusNam', models.CharField(max_length=255)),
            ],
        ),
    ]
