# Generated by Django 5.1.5 on 2025-06-19 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
        ('busstop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_time', models.IntegerField()),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buses.buses')),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstop.busstop')),
            ],
        ),
    ]
