# Generated by Django 5.2 on 2025-06-14 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
        ('busstop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_time', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buses.buses')),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstop.busstop')),
            ],
        ),
    ]
