# Generated by Django 5.2 on 2025-06-14 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='cart',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.buses'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='selected_time',
            field=models.CharField(max_length=50),
        ),
    ]
