# Generated by Django 5.2 on 2025-06-14 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
        ('cart', '0003_remove_cart_created_at_alter_cart_bus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buses.buses'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='selected_time',
            field=models.IntegerField(),
        ),
    ]
