# Generated by Django 5.2 on 2025-06-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_short_name_alter_cart_bus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='cart',
            name='selected_time',
            field=models.CharField(max_length=50),
        ),
    ]
