# Generated by Django 5.2 on 2025-06-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cart_short_name_alter_cart_selected_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='short_name',
            field=models.IntegerField(default=0),
        ),
    ]
