# Generated by Django 5.2 on 2025-06-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='selected_time',
            field=models.IntegerField(),
        ),
    ]
